<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_id = str_replace(' ', '_', $this->getClassName());
?>
<?php if(!$_productCollection->count()): return; endif; ?>

<div class="category-products block block-highlight <?php echo $this->getClassName() ?>">
    <div class="block-title"><strong><span><?php echo $this->__($this->getTitle()) ?></span></strong></div>
    <div class="block-content">
        <?php $_iterator = 0; ?>
        <ol class="products-list" id="<?php echo $_id ?>">
        <?php foreach ($_productCollection as $_product): ?>
            <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                <a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(50); ?>" width="50" height="50" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <div class="product-shop">
                    <div class="f-fix">
                        <h2 class="product-name"><a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                        <div class="desc std">
                            <?php echo nl2br($this->htmlEscape($this->getShortReviewText($_product->getDetail(), 80))) ?>
                            <?php /*echo $this->__('(Posted on %s)', $this->formatDate($_product->getCreatedAt()), 'long')*/ ?>
                            <a href="<?php echo $this->getReviewUrl($_product->getReviewId()) ?>" title="<?php echo $this->htmlEscape($_product->getTitle()) ?>" class="link-learn"><?php echo $this->__('Review Details') ?></a>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('<?php echo $_id ?>', 'none-recursive')</script>
    </div>
</div>
