<div class="entry-edit custom-options siblings-options">
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('navigationpro')->__('Siblings') ?></h4>
        <div class="right"><?php echo $this->getAddButtonHtml() ?></div>
    </div>

    <div id="siblings_container" class="box">
        <div id="siblings_container_top"></div>
        <?php echo $this->getSiblingsHtml() ?>
    </div>
</div>
