<?php
/**
 * DO NOT REMOVE OR MODIFY THIS NOTICE
 *
 * EasyBanner module for Magento - flexible banner management
 *
 * @author Templates-Master Team <www.templates-master.com>
 */
?>

<?php
$onclick = '';
$options = '\'\'';
if ($this->getTarget() == 'popup') {
    $options = '\'width=600,height=400\'';
}
if ($this->getTarget() != 'self') {
    $onclick = 'onclick="return !window.open(this.href, \'easybanners'.$this->getBannerId().'\', '.$options.')"';
}

$height = $this->getHeight();
$width  = $this->getWidth();
?>

<a rel="nofollow" href="<?php echo $this->getUrl() . $this->getBannerUrl() ?>" title="<?php echo $this->getTitle() ?>" <?php echo $onclick ?>>
<?php if(!$this->getResizeImage()): ?>
    <?php
    $style = '';
    if (!empty($width)):
        $style = 'width: ' . $width . 'px';
    elseif (!empty($height)):
        $style = 'height: ' . $height . 'px';
    endif;
    ?>
    <img src="<?php echo $this->getImage() ?>" style="<?php echo $style ?>" alt="<?php echo $this->htmlEscape($this->getTitle()) ?>" />
<?php else: ?>
    <?php
    $multiplier = 1;
    if ($this->getRetinaSupport()) :
        $multiplier = 2;
    endif;
    ?>
    <img src="<?php echo $this->resizeImage($width * $multiplier, $height * $multiplier) ?>" width="<?php echo $width ?>"<?php echo $height ? " height='$height'" : '' ?> alt="<?php echo $this->htmlEscape($this->getTitle()) ?>" />
<?php endif; ?>
</a>