<?php if (Mage::getStoreConfig('prolabels/general/enabled')) : ?>
<script type="text/javascript">
    function initProLabelsTooltip(){
        var ProlabelsTooltip = new ProLabelsTooltip({
            'background' : '<?php echo Mage::getStoreConfig('prolabels/tooltip/background') ?>',
            'color'      : '<?php echo Mage::getStoreConfig('prolabels/tooltip/color') ?>'
        });
    }

    if (Prototype.Browser.IE) {
        Event.observe(window, 'load', function(){
            initProLabelsTooltip();
        });
    } else {
        document.observe("dom:loaded", function(){
            initProLabelsTooltip();
        });
    }
</script>
<?php endif; ?>