<?php if (Mage::getStoreConfig('tm_ajaxsearch/general/enabled')) :?>
<form id="search_mini_form" action="<?php echo $this->helper('catalogSearch')->getResultUrl() ?>" method="get">
    <fieldset>
        <legend><?php echo $this->__('Search Site') ?></legend>
        <div class="mini-search form-search">
            <div id="searchajaxico" class=""></div>
            <label for="search"><?php echo $this->__('Search:') ?></label>
            <?php if (Mage::getStoreConfigFlag('tm_ajaxsearch/general/show_category_filter')) : ?>
                <?php echo $this->getChildHtml('ajaxsearch_category_filter') ?>
                <script type="text/javascript">
                    Prototype.Browser.IE6 = Prototype.Browser.IE && parseInt(navigator.userAgent.substring(navigator.userAgent.indexOf("MSIE")+5)) == 6;
                    Prototype.Browser.IE7 = Prototype.Browser.IE && parseInt(navigator.userAgent.substring(navigator.userAgent.indexOf("MSIE")+5)) == 7;
                    if (!Prototype.Browser.IE6 && !Prototype.Browser.IE7) {
                        new Chosen($('search_mini_form').down('.ajaxsearch-category-select'), {
                            allow_single_deselect: true,
                            no_results_text: "<?php echo $this->__('No results match') ?>"
                        });
                    }
                </script>
            <?php endif; ?>
            <input id="search" type="text" class="input-text" name="<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>" value="<?php echo Mage::getStoreConfig('tm_ajaxsearch/general/searchfieldtext'); ?>" />
            <button type="button" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    <?php $_isSecure = $this->getRequest()->isSecure(); ?>
    function initAutocomplete(){
        new AjaxsearchAutocomplete('search', {
            serviceUrl   : '<?php echo $this->getUrl('ajaxsearch', array('_secure' => $_isSecure)); ?>',
            enableloader : <?php echo Mage::getStoreConfig('tm_ajaxsearch/general/enableloader') ? 'true' : 'false'; ?>,
            minChars     : <?php echo Mage::getStoreConfig('tm_ajaxsearch/general/minchars'); ?>,
            maxHeight    : <?php echo Mage::getStoreConfig('tm_ajaxsearch/general/maxheight'); ?>,
            width        : <?php echo Mage::getStoreConfig('tm_ajaxsearch/general/width'); ?>,
            searchtext   : '<?php echo Mage::getStoreConfig('tm_ajaxsearch/general/searchfieldtext'); ?>',
            onSelect     : function (value, data) {setLocation(value.url);}
        });
    }
    if (Prototype.Browser.IE) {
        Event.observe(window, 'load', initAutocomplete);
    } else {
        document.observe("dom:loaded", initAutocomplete);
    }
//]]>
</script>
<?php endif; ?>