<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): return; endif; ?>

<div class="category-products block-highlight <?php echo $this->getClassName() ?>">
    <div class="block-title"><span><?php echo $this->__($this->getTitle()) ?></span></div>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <div class="block-content cols-<?php echo $_columnCount ?>">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid grid-wide">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(190); ?>" width="80" height="80" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <div class="product-shop">
                    <div class="f-fix">
                        <h2 class="product-name"><a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                        <div class="desc std">
                            <?php echo nl2br($this->htmlEscape($this->getShortReviewText($_product->getDetail(), 80))) ?>
                            <?php /*echo $this->__('(Posted on %s)', $this->formatDate($_product->getCreatedAt()), 'long')*/ ?>
                            <a href="<?php echo $this->getReviewUrl($_product->getReviewId()) ?>" title="<?php echo $this->htmlEscape($_product->getTitle()) ?>" class="link-learn"><?php echo $this->__('Review Details') ?></a>
                        </div>
                    </div>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    </div>
</div>
